[project]
name = "gwemfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arviz",
    "astropy",
    "blackjax-nightly",
    "corner",
    "dvc-ssh",
    "helens",
    "herculens",
    "ipykernel",
    "jaxtronomy",
    "jupyter",
    "ler",
    "matplotlib",
    "nbconvert",
    "nifty8",
    "numpy",
    "numpyro",
    "optax",
    "scienceplots",
    "scipy",
    "utax",
    "herculens @ git+https://github.com/austinpeel/herculens.git",
    "utax @ git+https://github.com/aymgal/utax.git",
    "helens @ git+https://github.com/Herculens/helens",
    "arviz",
    "ipython>=9.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
