stages:
  make corner plots:
    cmd: uv run example_usage_gw_only.py
    deps:
    - example_usage_gw_only.py
    outs:
    - approx_banana_results.pkl
    - cosmology_params.pdf
    - lens_mass.pdf
